#ifndef CONFIGURATION_H
#define CONFIGURATION_H

#define GPIO_ONBOARD_LED  21
#define GPIO_EXTERNAL_LED 43

#define GPIO_MOUSE_SWITCH_LEFT  1
#define GPIO_MOUSE_SWITCH_RIGHT 2

#define GPIO_KEY_SWITCH_0 7
#define GPIO_KEY_SWITCH_1 8 
#define GPIO_KEY_SWITCH_2 9

#define GPIO_ROTARY_ENCA 3
#define GPIO_ROTARY_ENCB 4
#define GPIO_ROTARY_SWITCH 44

#define I2C_MASTER_SDA_GPIO 5
#define I2C_MASTER_SCL_GPIO 6

#define I2C_MASTER_PORT             I2C_NUM_0
#define I2C_MASTER_FREQ_HZ          400000
#define I2C_MASTER_TX_BUF_DISABLE   0
#define I2C_MASTER_RX_BUF_DISABLE   0
#define I2C_MASTER_TIMEOUT_MS       pdMS_TO_TICKS(1000)

#define I2C_ADDRESS_TLV493D  0x5E

#endif